import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import type { GetStaticProps } from "next";
import { IPost } from "../types/article";
import PostList from "../components/PostList";

interface Props extends GetStaticProps {
  posts: IPost[];
}

export default function Home({ posts }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.length && <PostList posts={posts} />}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

async function fetchPosts(limit?: string) {
  const url = limit
    ? `https://jsonplaceholder.typicode.com/posts?_limit=${limit}`
    : `https://jsonplaceholder.typicode.com/posts`;
  const res = await fetch(url);
  const posts = await res.json();
  return posts;
}

// Fetches data at build
export const getStaticProps = async () => {
  const posts = await fetchPosts("6");
  return {
    props: {
      posts: posts || [],
    },
  };
};
